// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	user.proto

It has these top-level messages:
	AddUserReq
	UpdateUserReq
	ReadUserResp
	ReadUserByIDResp
	ReadUserByIDReq
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc1 "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 4.
type AddUserReq struct {
	ID         string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Pwd        string `protobuf:"bytes,3,opt,name=Pwd" json:"Pwd,omitempty"`
	IDkaryawan string `protobuf:"bytes,4,opt,name=IDkaryawan" json:"IDkaryawan,omitempty"`
	Status     int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	CreatedBy  string `protobuf:"bytes,6,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn  string `protobuf:"bytes,7,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdatedBy  string `protobuf:"bytes,8,opt,name=UpdatedBy" json:"UpdatedBy,omitempty"`
	UpdatedOn  string `protobuf:"bytes,9,opt,name=UpdatedOn" json:"UpdatedOn,omitempty"`
	Keterangan string `protobuf:"bytes,10,opt,name=Keterangan" json:"Keterangan,omitempty"`
}

func (m *AddUserReq) Reset()                    { *m = AddUserReq{} }
func (m *AddUserReq) String() string            { return proto.CompactTextString(m) }
func (*AddUserReq) ProtoMessage()               {}
func (*AddUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AddUserReq) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AddUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddUserReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *AddUserReq) GetIDkaryawan() string {
	if m != nil {
		return m.IDkaryawan
	}
	return ""
}

func (m *AddUserReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *AddUserReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *AddUserReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *AddUserReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *AddUserReq) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *AddUserReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type UpdateUserReq struct {
	ID         string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Pwd        string `protobuf:"bytes,3,opt,name=Pwd" json:"Pwd,omitempty"`
	IDkaryawan string `protobuf:"bytes,4,opt,name=IDkaryawan" json:"IDkaryawan,omitempty"`
	Status     int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	CreatedBy  string `protobuf:"bytes,6,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn  string `protobuf:"bytes,7,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdatedBy  string `protobuf:"bytes,8,opt,name=UpdatedBy" json:"UpdatedBy,omitempty"`
	UpdatedOn  string `protobuf:"bytes,9,opt,name=UpdatedOn" json:"UpdatedOn,omitempty"`
	Keterangan string `protobuf:"bytes,10,opt,name=Keterangan" json:"Keterangan,omitempty"`
}

func (m *UpdateUserReq) Reset()                    { *m = UpdateUserReq{} }
func (m *UpdateUserReq) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserReq) ProtoMessage()               {}
func (*UpdateUserReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateUserReq) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *UpdateUserReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *UpdateUserReq) GetIDkaryawan() string {
	if m != nil {
		return m.IDkaryawan
	}
	return ""
}

func (m *UpdateUserReq) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UpdateUserReq) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *UpdateUserReq) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *UpdateUserReq) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *UpdateUserReq) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *UpdateUserReq) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type ReadUserResp struct {
	AllUser []*ReadUserByIDResp `protobuf:"bytes,1,rep,name=allUser" json:"allUser,omitempty"`
}

func (m *ReadUserResp) Reset()                    { *m = ReadUserResp{} }
func (m *ReadUserResp) String() string            { return proto.CompactTextString(m) }
func (*ReadUserResp) ProtoMessage()               {}
func (*ReadUserResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReadUserResp) GetAllUser() []*ReadUserByIDResp {
	if m != nil {
		return m.AllUser
	}
	return nil
}

type ReadUserByIDResp struct {
	ID         string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Username   string `protobuf:"bytes,2,opt,name=Username" json:"Username,omitempty"`
	Pwd        string `protobuf:"bytes,3,opt,name=Pwd" json:"Pwd,omitempty"`
	IDkaryawan string `protobuf:"bytes,4,opt,name=IDkaryawan" json:"IDkaryawan,omitempty"`
	Status     int32  `protobuf:"varint,5,opt,name=Status" json:"Status,omitempty"`
	CreatedBy  string `protobuf:"bytes,6,opt,name=CreatedBy" json:"CreatedBy,omitempty"`
	CreatedOn  string `protobuf:"bytes,7,opt,name=CreatedOn" json:"CreatedOn,omitempty"`
	UpdatedBy  string `protobuf:"bytes,8,opt,name=UpdatedBy" json:"UpdatedBy,omitempty"`
	UpdatedOn  string `protobuf:"bytes,9,opt,name=UpdatedOn" json:"UpdatedOn,omitempty"`
	Keterangan string `protobuf:"bytes,10,opt,name=Keterangan" json:"Keterangan,omitempty"`
}

func (m *ReadUserByIDResp) Reset()                    { *m = ReadUserByIDResp{} }
func (m *ReadUserByIDResp) String() string            { return proto.CompactTextString(m) }
func (*ReadUserByIDResp) ProtoMessage()               {}
func (*ReadUserByIDResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadUserByIDResp) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ReadUserByIDResp) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ReadUserByIDResp) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *ReadUserByIDResp) GetIDkaryawan() string {
	if m != nil {
		return m.IDkaryawan
	}
	return ""
}

func (m *ReadUserByIDResp) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReadUserByIDResp) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *ReadUserByIDResp) GetCreatedOn() string {
	if m != nil {
		return m.CreatedOn
	}
	return ""
}

func (m *ReadUserByIDResp) GetUpdatedBy() string {
	if m != nil {
		return m.UpdatedBy
	}
	return ""
}

func (m *ReadUserByIDResp) GetUpdatedOn() string {
	if m != nil {
		return m.UpdatedOn
	}
	return ""
}

func (m *ReadUserByIDResp) GetKeterangan() string {
	if m != nil {
		return m.Keterangan
	}
	return ""
}

type ReadUserByIDReq struct {
	ID string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
}

func (m *ReadUserByIDReq) Reset()                    { *m = ReadUserByIDReq{} }
func (m *ReadUserByIDReq) String() string            { return proto.CompactTextString(m) }
func (*ReadUserByIDReq) ProtoMessage()               {}
func (*ReadUserByIDReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadUserByIDReq) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*AddUserReq)(nil), "grpc.AddUserReq")
	proto.RegisterType((*UpdateUserReq)(nil), "grpc.UpdateUserReq")
	proto.RegisterType((*ReadUserResp)(nil), "grpc.ReadUserResp")
	proto.RegisterType((*ReadUserByIDResp)(nil), "grpc.ReadUserByIDResp")
	proto.RegisterType((*ReadUserByIDReq)(nil), "grpc.ReadUserByIDReq")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc1.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc1.SupportPackageIsVersion4

// Client API for UserService service

type UserServiceClient interface {
	AddUser(ctx context.Context, in *AddUserReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error)
	ReadUser(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadUserResp, error)
	ReadUserByID(ctx context.Context, in *ReadUserByIDReq, opts ...grpc1.CallOption) (*ReadUserByIDResp, error)
}

type userServiceClient struct {
	cc *grpc1.ClientConn
}

func NewUserServiceClient(cc *grpc1.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AddUser(ctx context.Context, in *AddUserReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.UserService/AddUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc1.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc1.Invoke(ctx, "/grpc.UserService/UpdateUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadUser(ctx context.Context, in *google_protobuf.Empty, opts ...grpc1.CallOption) (*ReadUserResp, error) {
	out := new(ReadUserResp)
	err := grpc1.Invoke(ctx, "/grpc.UserService/ReadUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReadUserByID(ctx context.Context, in *ReadUserByIDReq, opts ...grpc1.CallOption) (*ReadUserByIDResp, error) {
	out := new(ReadUserByIDResp)
	err := grpc1.Invoke(ctx, "/grpc.UserService/ReadUserByID", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceServer interface {
	AddUser(context.Context, *AddUserReq) (*google_protobuf.Empty, error)
	UpdateUser(context.Context, *UpdateUserReq) (*google_protobuf.Empty, error)
	ReadUser(context.Context, *google_protobuf.Empty) (*ReadUserResp, error)
	ReadUserByID(context.Context, *ReadUserByIDReq) (*ReadUserByIDResp, error)
}

func RegisterUserServiceServer(s *grpc1.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_AddUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddUser(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/AddUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddUser(ctx, req.(*AddUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadUser(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/ReadUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadUser(ctx, req.(*google_protobuf.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReadUserByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc1.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserByIDReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReadUserByID(ctx, in)
	}
	info := &grpc1.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.UserService/ReadUserByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReadUserByID(ctx, req.(*ReadUserByIDReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc1.ServiceDesc{
	ServiceName: "grpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc1.MethodDesc{
		{
			MethodName: "AddUser",
			Handler:    _UserService_AddUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "ReadUser",
			Handler:    _UserService_ReadUser_Handler,
		},
		{
			MethodName: "ReadUserByID",
			Handler:    _UserService_ReadUserByID_Handler,
		},
	},
	Streams:  []grpc1.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x54, 0xdb, 0x4a, 0xeb, 0x40,
	0x14, 0x6d, 0xd2, 0xfb, 0xee, 0xb9, 0x94, 0x7d, 0x38, 0x65, 0xc8, 0x39, 0x48, 0xcd, 0x53, 0x9f,
	0x52, 0xa9, 0x08, 0x82, 0x08, 0x5a, 0xe3, 0x43, 0xf0, 0x21, 0x92, 0xd2, 0x0f, 0x98, 0x36, 0x63,
	0x10, 0xdb, 0x49, 0x9c, 0xa4, 0x96, 0xfc, 0x8a, 0x20, 0xf8, 0x9d, 0x3e, 0xc9, 0xe4, 0xd2, 0x34,
	0x5a, 0xfd, 0x82, 0xbe, 0x65, 0xaf, 0xb5, 0x36, 0xb3, 0xb3, 0x66, 0xcd, 0x06, 0x58, 0x85, 0x4c,
	0x18, 0x81, 0xf0, 0x23, 0x1f, 0x6b, 0x9e, 0x08, 0xe6, 0xda, 0x3f, 0xcf, 0xf7, 0xbd, 0x05, 0x1b,
	0x26, 0xd8, 0x6c, 0x75, 0x37, 0x64, 0xcb, 0x20, 0x8a, 0x53, 0x89, 0xfe, 0xac, 0x02, 0x5c, 0xba,
	0xee, 0x34, 0x64, 0xc2, 0x61, 0x8f, 0xf8, 0x0b, 0x54, 0xcb, 0x24, 0x4a, 0x5f, 0x19, 0xb4, 0x1d,
	0xd5, 0x32, 0x51, 0x83, 0x96, 0xa4, 0x38, 0x5d, 0x32, 0xa2, 0x26, 0xe8, 0xa6, 0xc6, 0x2e, 0x54,
	0x6f, 0xd7, 0x2e, 0xa9, 0x26, 0xb0, 0xfc, 0xc4, 0x03, 0x00, 0xcb, 0x7c, 0xa0, 0x22, 0xa6, 0x6b,
	0xca, 0x49, 0x2d, 0x21, 0xb6, 0x10, 0xec, 0x41, 0x63, 0x12, 0xd1, 0x68, 0x15, 0x92, 0x7a, 0x5f,
	0x19, 0xd4, 0x9d, 0xac, 0xc2, 0xff, 0xd0, 0xbe, 0x12, 0x8c, 0x46, 0xcc, 0x1d, 0xc7, 0xa4, 0x91,
	0xb4, 0x15, 0xc0, 0x16, 0x6b, 0x73, 0xd2, 0x2c, 0xb1, 0x36, 0x97, 0xec, 0x34, 0x70, 0xb3, 0xde,
	0x56, 0xca, 0x6e, 0x80, 0x2d, 0xd6, 0xe6, 0xa4, 0x5d, 0x62, 0x6d, 0x2e, 0xe7, 0xbd, 0x61, 0x11,
	0x13, 0x94, 0x7b, 0x94, 0x13, 0x48, 0xe7, 0x2d, 0x10, 0xfd, 0x45, 0x85, 0x9f, 0xa9, 0x7a, 0xef,
	0xcf, 0x2e, 0x7f, 0x2e, 0xe0, 0x87, 0xc3, 0x68, 0x16, 0x9e, 0x30, 0xc0, 0x23, 0x68, 0xd2, 0xc5,
	0x42, 0x96, 0x44, 0xe9, 0x57, 0x07, 0x9d, 0x51, 0xcf, 0x90, 0x09, 0x34, 0x72, 0xd1, 0x38, 0xb6,
	0x4c, 0x29, 0x74, 0x72, 0x99, 0xfe, 0xaa, 0x42, 0xf7, 0x23, 0xbb, 0x37, 0xb9, 0x64, 0xf2, 0x21,
	0xfc, 0x2e, 0x3b, 0xf4, 0x29, 0x85, 0xa3, 0x37, 0x05, 0x3a, 0x92, 0x9f, 0x30, 0xf1, 0x74, 0x3f,
	0x67, 0x78, 0x02, 0xcd, 0xec, 0x4d, 0x63, 0x37, 0xbd, 0x81, 0xe2, 0x89, 0x6b, 0x3d, 0x23, 0xdd,
	0x07, 0x46, 0xbe, 0x0f, 0x8c, 0x6b, 0xb9, 0x0f, 0xf4, 0x0a, 0x9e, 0x01, 0x14, 0x69, 0xc7, 0x3f,
	0x69, 0x67, 0x29, 0xff, 0xdf, 0x34, 0x9f, 0x42, 0x2b, 0x1f, 0x13, 0xbf, 0x50, 0x69, 0x58, 0x8e,
	0x83, 0xbc, 0x6c, 0xbd, 0x82, 0xe7, 0x45, 0x8a, 0xe4, 0x0f, 0xe2, 0xdf, 0x5d, 0xa1, 0x49, 0x8e,
	0xde, 0x95, 0xa5, 0x59, 0x23, 0x39, 0xe4, 0xf8, 0x3d, 0x00, 0x00, 0xff, 0xff, 0x02, 0xe2, 0xd6,
	0xa7, 0xf9, 0x04, 0x00, 0x00,
}
